### PR TITLE
Fix GetInt32

### PR DESCRIPTION
**Pull request by dupondje**
Otherwise GetInt32 always returns nil :)

### CODE REVIEW

**Comment by cblomart** [comment]
Good catch again!

Wouln't it be better to assign as i've done for the other types (i change v to &typed bellow in cache.go:58) ?
```golang
	case []string:
		if len(typed) > 0 {
			c.add(vcenter, section, i, &typed)
		}
	case int32:
		c.add(vcenter, section, i, &typed)
	case types.ManagedObjectReference:
                c.add(vcenter, section, i, &(typed.Value))
```

**Comment by dupondje** [comment]
Yea that would fix it also I guess :)
Maybe a bit more in line with the rest.

**Comment by cblomart** [comment]
I feel a bit stubborn rejecting a second pul from you...
Would you mind testing the change i just made?

**Comment by dupondje** [comment]
Hehe no problem! As long as the issues get solved :)

Confirmed that the latest commit fixes it!

**Pull request closed without merging**
