### PR TITLE
Create Elasticsearch Indexes with Mappings via struct Tags and correct Timestamp format

### PR DESCRIPTION
**Pull request by fdmsantos**
Changes:
   - Indexes are created with mapping. The mapping use the elastic tag in point struct.
   - Fix Timestamp format.

### CODE REVIEW

**Comment by cblomart** [comment]
Thanks a lot @fdmsantos.
To be frank i didn't have much time lately to work on vsphere-graphite.

Can you confirm this was tested  with elasticsearch? (i still don't have an elasticsearch implementation where i have a large vcenter)

Maybe we can also check with @MnrGreg if this suits his needs (@MnrGreg can you update us on this).

Lastly (i know this is annoying), can you check the code so "checks" get trough? (mainly code formating issues).

Thanks again!

**Comment by fdmsantos** [comment]
Hi @cblomart ,

Code Fixed it.

Yes was tested, and i have it in production. 
This PR is important to me , because i need have timestamp field created with type date.

Thank you for all work in this project.

Regards

**Comment by MnrGreg** [comment]
Good work @fdmsantos. I'll try it out my side as well.

**Comment by cblomart** [comment]
Great !!!

I’ll just wait for an update from @MnrGreg and merge the pull request and make a release.

**Comment by MnrGreg** [comment]
Been running for a few hours without issue. So LGTM.

On a site note I noticed every VM metric is being captured with the NumCPU and MemorySizeMB fields. This information is already captured with the Cpu and Mem groups for each VM and results in a lot of extra storage. Is this needed for some other backends or would it make sense to remove?

**Comment by fdmsantos** [comment]
Sorry i understand badly the question. I thought you are talking about the PR Feature. About the NumCpu and MemorySizeFieldMB fields, this is default behavior. I didn, t make Changes in the collect

**Comment by cblomart** [comment]
Ok merging.

I'll open a issue on the numcpu and memorysizemb.

**Pull request merged**
