### PR TITLE
Adds ElasticSearch backend to vsphere-graphite

### PR DESCRIPTION
**Pull request by MnrGreg**
Adds ElasticSearch backend to vsphere-graphite

Not yet optimal but does the job. Currently each metric within a sample period is submitted/indexed individually. In future will look to use the elastic bulkindexrequest. This will upload/index all metrics per sample period in a single call.

Uses the backend.Database field in the JSON for the ElasicSearch Index name.

Elastic Search field mapping provided for easy import into Elastic: vsphere-graphite-elastic-index-mappings.json

Relates to #28

### CODE REVIEW

**Comment by cblomart** [comment]
Can you add github.com/olivere/elastic to the makefile script so build goes throught?

I'll look at the code.

**Comment by cblomart** [comment]
Some questions:
- is it a bad idea to just send the point as defined in vsphere-graphite to elasticsearch? Seems to me that reconstructing a view of the point to influx consumes resources (at least declaring means a memory allocation for each point)
- can you use ffjson to marshal to json? it is already used in other places in the project.

**Comment by cblomart** [comment]
i corrected the issue with null pointers (unitialized loggers in utils).

Can you give me an update on the idea to push points directly to elasticsearch in place of creating a new object?

**Comment by MnrGreg** [comment]
Hi @cblomart 

One needs to use this function https://github.com/olivere/elastic/wiki/BulkIndex to upload the JSON in bulk. I'm not sure how one would push the points directly?

**Comment by cblomart** [comment]
I see that you are reconstructing a document to index into elastic (variable m). I meant to ask if you could make use of the point (variable) directly to index it into elastic.

I got the feeling it could simplify the index that seems currently orientiend to certain metrics.

On a side note, did you see null points which may have led you to check if a point is null which shouldn’t happen... to see also how the Doc function handle null input.

**Comment by cblomart** [comment]
I will commit to elasic branch. I'd like to check:
 - use the point object directly to send to elastic in place of creating an intermediary object (m)
 - auto index creation (no need to create the index)

**Pull request merged**
