### PR TITLE
Add option for fluentd backend

### PR DESCRIPTION
**Pull request by jlothian**
Add a fluentd backend.  It's fairly straightforward - the fluentd client
doesn't seem to have a concept of bulk operations, so we just send a new
message for point.

Comments welcome - I don't really know Go at all.

### CODE REVIEW

**Comment by cblomart** [comment]
other backend uses "vsphere" to prefix metrix (graphite, prometheus), does it fit with fluentd tag usage?

if it does i would either see:
* a global tag config for all backends (that uses tag or prefixing)
* a static prefix or tag, here "vsphere"

**Comment by jlothian** [comment]
I know in our use case, I need to be able to specify different tags.  What about a follow-up PR that allows for a global tag config for all backends, with a default of vsphere?  I could also combine with this PR if you prefer.

**Comment by cblomart** [comment]
I updated the fluentd branch with what was on my mind.
Tag is changed to Prefix and is used by frontend having a default frontend.

**Comment by jlothian** [comment]
That looks good to me, more sensible than Tag.

**Pull request merged**
